import { RecurrencePattern } from '@/constants/constants';

  export interface Event {
    title: string;
    date: Date;
    location: string;
    fee?: number;
    summary: string;
    description: string;
    isRecurring?: boolean;
    recurrencePattern?: RecurrencePattern;
    image?: File
  }

  export interface EventWithId extends Event {
    _id: string; // This will be generated by the database
}